# Generated by Django 3.0.3 on 2020-02-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablero',
            name='nombre_tablero',
            field=models.CharField(max_length=50, verbose_name=''),
        ),
    ]
